import 'package:elearning/src/data/models/disney_characters_response.dart';
import 'package:elearning/src/data/repository/disney_repository.dart';
import 'package:elearning/src/data/repository/disney_repository_impl.dart';
import 'package:elearning/src/networking/dio_client.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  late DisneyRepository disneyRepository;
  late DioClient dioClient;

  setUp(() {
    dioClient = DioClientImpl();
    disneyRepository = DisneyRepositoryImpl(dioClient: dioClient);
  });


  test('Get all characters', () async {
    expect(
      await disneyRepository.getAllCharacters(),
      List<CharacterData>.from((charactersResponseJson['data']! as List).map((e) => CharacterData.fromMap(e))),
    );
  });
}

final charactersResponseJson = {
  "data": [
    {
      "films": [],
      "shortFilms": [],
      "tvShows": [],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 6,
      "name": "'Olu Mel",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/6/61/Olu_main.png",
      "url": "https://api.disneyapi.dev/characters/6"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Gravity Falls"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 7,
      "name": ".GIFfany",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/5/51/Giffany.png",
      "url": "https://api.disneyapi.dev/characters/7"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Lilo & Stitch: The Series", "Stitch!"],
      "videoGames": ["Disney Tsum Tsum (game)"],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 10,
      "name": "627",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/8/80/Profile_-_627.png",
      "url": "https://api.disneyapi.dev/characters/10"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": [],
      "videoGames": [],
      "parkAttractions": ["The Timekeeper"],
      "allies": [],
      "enemies": [],
      "_id": 11,
      "name": "9-Eye",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/7/77/9-eye.jpg",
      "url": "https://api.disneyapi.dev/characters/11"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Pickle and Peanut"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 12,
      "name": "90's Adventure Bear",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/3/3f/90%27s_Adventure_Bear_profile.png",
      "url": "https://api.disneyapi.dev/characters/12"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": [],
      "videoGames": ["Epic Mickey 2: The Power of Two"],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 13,
      "name": "A.B.E.",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/2/20/ABE.jpg",
      "url": "https://api.disneyapi.dev/characters/13"
    },
    {
      "films": ["The Computer Wore Tennis Shoes", "Now You See Him, Now You Don't", "The Strongest Man in the World"],
      "shortFilms": [],
      "tvShows": [],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 14,
      "name": "A.J. Arno",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/2/2c/A.J._Arno.jpg",
      "url": "https://api.disneyapi.dev/characters/14"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Puppy Dog Pals"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 15,
      "name": "A.R.F.",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/b/ba/A.R.F.png",
      "url": "https://api.disneyapi.dev/characters/15"
    },
    {
      "films": ["Cheetah"],
      "shortFilms": [],
      "tvShows": [],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 16,
      "name": "Abdullah",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/c/cb/1087603-44532-clp-950.jpg",
      "url": "https://api.disneyapi.dev/characters/16"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["The Legend of Tarzan"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 17,
      "name": "Abigail Markham",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/9/95/Abigail_Markham.jpeg",
      "url": "https://api.disneyapi.dev/characters/17"
    },
    {
      "films": ["The Fox and the Hound", "The Fox and the Hound 2"],
      "shortFilms": [],
      "tvShows": [],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 18,
      "name": "Abigail the Cow",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/0/05/Fox-disneyscreencaps_com-901.jpg",
      "url": "https://api.disneyapi.dev/characters/18"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Once Upon a Time"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 19,
      "name": "Abigail",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/d/dd/Regalblond.jpg",
      "url": "https://api.disneyapi.dev/characters/19"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Elena of Avalor"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 20,
      "name": "Queen Abigail",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/f/fa/Normal_EoA_S3_E4_0217.jpg",
      "url": "https://api.disneyapi.dev/characters/20"
    },
    {
      "films": ["The Return of Jafar", "Aladdin and the King of Thieves"],
      "shortFilms": [],
      "tvShows": ["Aladdin (TV series)"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 21,
      "name": "Abis Mal's Thugs",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/b/ba/Abis_Mal%27s_Thugs.jpg",
      "url": "https://api.disneyapi.dev/characters/21"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Tron: Uprising"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 22,
      "name": "Able",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/a/af/Able.png",
      "url": "https://api.disneyapi.dev/characters/22"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": [],
      "videoGames": ["Tron: Evolution"],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 23,
      "name": "Abraxas",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/c/ce/Abraxas.jpg",
      "url": "https://api.disneyapi.dev/characters/23"
    },
    {
      "films": ["Alice in Wonderland (2010 film)", "Alice Through the Looking Glass"],
      "shortFilms": [],
      "tvShows": [],
      "videoGames": ["Alice in Wonderland (2010 video game)", "Disney Universe", "Disney Crossy Road"],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 24,
      "name": "Absolem",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/4/4d/Caterpillar.jpg",
      "url": "https://api.disneyapi.dev/characters/24"
    },
    {
      "films": [
        "Aladdin (film)",
        "The Return of Jafar",
        "Aladdin and the King of Thieves",
        "Mickey's Magical Christmas: Snowed in at the House of Mouse",
        "Disney Princess Enchanted Tales: Follow Your Dreams",
        "Aladdin (2019 film)"
      ],
      "shortFilms": [],
      "tvShows": ["Aladdin (TV series)", "Hercules (TV series)", "House of Mouse"],
      "videoGames": [
        "Aladdin (video game)",
        "Disney's ReadingQuest With Aladdin",
        "Disney's MathQuest With Aladdin",
        "Disney's Aladdin in Nasira's Revenge",
        "Kingdom Hearts (series)",
        "Disney Universe",
        "Disney Princess Enchanting Storybooks",
        "Epic Mickey: Power of Illusion",
        "disney:Hidden Worlds",
        "Disney Infinity (series)",
        "Disney Villains Challenge",
        "Disney Tsum Tsum (game)",
        "Disney Crossy Road",
        "Disney Magic Kingdoms",
        "Disney Emoji Blitz",
        "Disney Getaway Blast",
        "Disney Princess Majestic Quest"
      ],
      "parkAttractions": ["Garden of the Twelve Friends", "Voyage to the Crystal Grotto"],
      "allies": [],
      "enemies": [],
      "_id": 25,
      "name": "Abu",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/3/3f/Profile_-_Abu.png",
      "url": "https://api.disneyapi.dev/characters/25"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Gravity Falls"],
      "videoGames": ["Gravity Falls: Legend of the Gnome Gemulets"],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 26,
      "name": "Abuelita",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/c/cd/Profile_-_Abuelita.png",
      "url": "https://api.disneyapi.dev/characters/26"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Handy Manny"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 27,
      "name": "Abuelito",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/c/c8/Char_51942_thumb.jpg",
      "url": "https://api.disneyapi.dev/characters/27"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Big Hero 6: The Series"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 28,
      "name": "AC and DC",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/7/75/Profile_-_AC_and_DC.jpg",
      "url": "https://api.disneyapi.dev/characters/28"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Kim Possible"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 29,
      "name": "Professor Acari",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/5/5d/Professor_Acari.jpg",
      "url": "https://api.disneyapi.dev/characters/29"
    },
    {
      "films": ["Leroy & Stitch"],
      "shortFilms": [],
      "tvShows": ["Lilo & Stitch: The Series", "Stitch!"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 30,
      "name": "Ace",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/1/1e/Profile_-_Ace.png",
      "url": "https://api.disneyapi.dev/characters/30"
    },
    {
      "films": ["The Hunchback of Notre Dame", "The Hunchback of Notre Dame II"],
      "shortFilms": [],
      "tvShows": [],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 31,
      "name": "Achilles",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/8/8f/Achilles_HOND.jpg",
      "url": "https://api.disneyapi.dev/characters/31"
    },
    {
      "films": ["Aladdin (film)", "Aladdin (2019 film)"],
      "shortFilms": [],
      "tvShows": ["Once Upon a Time"],
      "videoGames": ["Disney Crossy Road"],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 33,
      "name": "Prince Achmed",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/7/76/Aladdin-disneyscreencaps.com-1123.jpg",
      "url": "https://api.disneyapi.dev/characters/33"
    },
    {
      "films": ["Saludos Amigos"],
      "shortFilms": [],
      "tvShows": [],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 34,
      "name": "Aconcagua",
      "imageUrl":
      "https://static.wikia.nocookie.net/disney/images/3/32/Saludos-Amigos-classic-disney-18407142-800-600.jpg",
      "url": "https://api.disneyapi.dev/characters/34"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Tron: Uprising"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 35,
      "name": "Ada",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/f/f9/Ada.png",
      "url": "https://api.disneyapi.dev/characters/35"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["K.C. Undercover"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 36,
      "name": "Candace Adams",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/8/8b/Enemy_of_the_State_promo_3.jpg",
      "url": "https://api.disneyapi.dev/characters/36"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Dog With a Blog"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 37,
      "name": "Gator Adams",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/6/60/LeonaGatorAdams.jpg",
      "url": "https://api.disneyapi.dev/characters/37"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["The Suite Life on Deck"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 38,
      "name": "Addison",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/0/05/Addison_from_slod.jpg",
      "url": "https://api.disneyapi.dev/characters/38"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Hannah Montana"],
      "videoGames": ["Hannah Montana (video game)"],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 40,
      "name": "Amber Addison",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/5/52/250px-Amber.jpg",
      "url": "https://api.disneyapi.dev/characters/40"
    },
    {
      "films": ["Genius"],
      "shortFilms": [],
      "tvShows": [],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 41,
      "name": "Claire Addison",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/7/79/Claireaddison.jpeg",
      "url": "https://api.disneyapi.dev/characters/41"
    },
    {
      "films": ["Mickey's Good Deed"],
      "shortFilms": [],
      "tvShows": [],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 42,
      "name": "Adelbert",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/2/21/Adelbert.jpg",
      "url": "https://api.disneyapi.dev/characters/42"
    },
    {
      "films": [],
      "shortFilms": ["Mickey's Good Deed"],
      "tvShows": [],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 43,
      "name": "Adelbert's Father",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/9/96/Adelbertsfather.jpg",
      "url": "https://api.disneyapi.dev/characters/43"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Tangled: The Series"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 44,
      "name": "Adira",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/f/fa/Adira_Tangled.jpeg",
      "url": "https://api.disneyapi.dev/characters/44"
    },
    {
      "films": ["Mary Poppins (film)", "Mary Poppins Returns"],
      "shortFilms": [],
      "tvShows": [],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 45,
      "name": "Admiral Boom and Mr. Binnacle",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/b/be/Marypoppins-disneyscreencaps_com-1086.jpg",
      "url": "https://api.disneyapi.dev/characters/45"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Miles from Tomorrowland"],
      "videoGames": ["Miles from Tomorrowland: Missions"],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 46,
      "name": "Admirals Watson and Crick",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/c/c6/Admirals-Watson-and-Crick.png",
      "url": "https://api.disneyapi.dev/characters/46"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Hercules (TV series)"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 47,
      "name": "Adonis",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/c/ca/Adonis.jpg",
      "url": "https://api.disneyapi.dev/characters/47"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Star Darlings"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 48,
      "name": "Adora",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/6/6b/Profile-Adora.PNG",
      "url": "https://api.disneyapi.dev/characters/48"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Goldie & Bear"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 49,
      "name": "Adorable Norm",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/6/64/Adorable_Norm.png",
      "url": "https://api.disneyapi.dev/characters/49"
    },
    {
      "films": ["Hercules (film)"],
      "shortFilms": [],
      "tvShows": ["Hercules (TV series)"],
      "videoGames": ["Kingdom Hearts III"],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 112,
      "name": "Achilles",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/d/d3/Vlcsnap-2015-05-06-23h04m15s601.png",
      "url": "https://api.disneyapi.dev/characters/112"
    },
    {
      "films": ["Zombies", "Zombies 2", "Zombies 3"],
      "shortFilms": [],
      "tvShows": ["Addison's Moonstone Mystery (page does not exist)"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 119,
      "name": "Addison",
      "imageUrl":
      "https://static.wikia.nocookie.net/disney/images/e/e5/Addison%25_27s_More_Than_Cheer_%25_3F_Teaser_ZOMBIES_2_Disney_Channel.jpg",
      "url": "https://api.disneyapi.dev/characters/119"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Pair of Kings"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 130,
      "name": "Aerosol",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/9/92/Screenshot_2016-09-08_at_10.18.27_PM.png",
      "url": "https://api.disneyapi.dev/characters/130"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Jessie (TV series)"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 131,
      "name": "Agatha",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/4/40/J119.png",
      "url": "https://api.disneyapi.dev/characters/131"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Phineas and Ferb"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 132,
      "name": "Agent E",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/d/d4/Agent_E_salutes_Perry.jpg",
      "url": "https://api.disneyapi.dev/characters/132"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Lab Rats"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 133,
      "name": "Agent Gordon",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/5/51/Screenshot_2016-09-12_at_8.13.42_PM.png",
      "url": "https://api.disneyapi.dev/characters/133"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["The Replacements"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 134,
      "name": "Agent K",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/8/88/The-replacements-kath-soucie-0.jpg",
      "url": "https://api.disneyapi.dev/characters/134"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Quack Pack"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 135,
      "name": "Agent X",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/e/ef/Agent_X.png",
      "url": "https://api.disneyapi.dev/characters/135"
    },
    {
      "films": ["Bolt (film)"],
      "shortFilms": [],
      "tvShows": [],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 136,
      "name": "Agent",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/b/b2/Agent-%28Bolt%29.jpg",
      "url": "https://api.disneyapi.dev/characters/136"
    },
    {
      "films": [],
      "shortFilms": [],
      "tvShows": ["Miles from Tomorrowland"],
      "videoGames": [],
      "parkAttractions": [],
      "allies": [],
      "enemies": [],
      "_id": 137,
      "name": "Aggro",
      "imageUrl": "https://static.wikia.nocookie.net/disney/images/9/9c/Aggro.png",
      "url": "https://api.disneyapi.dev/characters/137"
    }
  ],
  "count": 50,
  "totalPages": 149,
  "nextPage": "https://api.disneyapi.dev/characters?page=2"
};
